version: '3.8'

services:
  eaos-postgres:
    image: pgvector/pgvector:0.5.1-pg16 # PostgreSQL 16 tích hợp sẵn pgvector cho tìm kiếm ngữ nghĩa
    container_name: eaos-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: eaos
      POSTGRES_PASSWORD: eaos_pass
      POSTGRES_DB: eaos_db
    ports:
      - "5432:5432"

  eaos-redis:
    image: redis:7.2-alpine
    container_name: eaos-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
