$doctor = @(
    "from pathlib import Path",
    "",
    "from dxs.domain.models import CheckStatus, Diagnostic, DoctorReport",
    "from dxs.ports.filesystem import FileSystem",
    "",
    "class DoctorService:",
    "",
    "    REQUIRED_FILES = (",
    '        "ARCHITECTURE_CONSTITUTION.md",',
    '        "ENGINEERING_GUIDE.md",',
    '        "PROJECT_CONTEXT.md",',
    "    )",
    "",
    "    def __init__(self, fs: FileSystem) -> None:",
    "        self._fs = fs",
    "",
    "    def run(self, root: Path) -> DoctorReport:",
    "        diagnostics = []",
    "",
    "        for name in self.REQUIRED_FILES:",
    "            path = root / name",
    "",
    "            if self._fs.is_file(path):",
    "                diagnostics.append(",
    "                    Diagnostic(",
    '                        f"DXS-DOC-{name}",',
    "                        CheckStatus.PASS,",
    '                        f"Document exists: {name}",',
    "                        str(path),",
    "                    )",
    "                )",
    "            else:",
    "                diagnostics.append(",
    "                    Diagnostic(",
    '                        f"DXS-DOC-{name}",',
    "                        CheckStatus.WARN,",
    '                        f"Document not found: {name}",',
    "                        str(path),",
    "                    )",
    "                )",
    "",
    "        return DoctorReport(tuple(diagnostics))"
) -join "`n"