"""Canonical Capability Taxonomy for EAOS Agent Capability Registry."""

from __future__ import annotations

from enum import StrEnum


class CapabilityCategory(StrEnum):
    """The 20 Canonical EAOS Agent Capability Categories."""

    ARCHITECTURE = "ARCHITECTURE"
    REPOSITORY = "REPOSITORY"
    CODE_ANALYSIS = "CODE_ANALYSIS"
    CODE_MODIFICATION = "CODE_MODIFICATION"
    REFACTORING = "REFACTORING"
    REWRITE = "REWRITE"
    RECOVERY = "RECOVERY"
    TESTING = "TESTING"
    RUNTIME = "RUNTIME"
    API = "API"
    WEBSOCKET = "WEBSOCKET"
    SECURITY = "SECURITY"
    DATABASE = "DATABASE"
    INFRASTRUCTURE = "INFRASTRUCTURE"
    DOCUMENTATION = "DOCUMENTATION"
    VERIFICATION = "VERIFICATION"
    FORENSICS = "FORENSICS"
    OBSERVABILITY = "OBSERVABILITY"
    MEMORY = "MEMORY"
    GOVERNANCE_ANALYSIS = "GOVERNANCE_ANALYSIS"


class AgentRoleCategory(StrEnum):
    """Canonical Specialized Agent Roles."""

    PLANNER = "PLANNER"
    ANALYZER = "ANALYZER"
    IMPLEMENTER = "IMPLEMENTER"
    TESTER = "TESTER"
    SECURITY_REVIEWER = "SECURITY_REVIEWER"
    ARCHITECTURE_REVIEWER = "ARCHITECTURE_REVIEWER"
    RUNTIME_OBSERVER = "RUNTIME_OBSERVER"
    VERIFIER = "VERIFIER"
    RECOVERY_AGENT = "RECOVERY_AGENT"
