from typing import Protocol

from packages.agent.domain.models import AIAgent


class AgentRegistryPort(Protocol):
    def register(self, agent: AIAgent) -> AIAgent: ...
    def find_by_id(self, agent_id: str) -> AIAgent | None: ...
    def list_all(self) -> list[AIAgent]: ...
    def update_lifecycle_state(self, agent_id: str, target_state: str) -> AIAgent: ...

