"""Facade Orchestrator cho miền SRC."""

from __future__ import annotations

from typing import Any

from application.use_cases.evaluate_security_policy_use_case import (
    EvaluateSecurityPolicyUseCase,
)
from automation.dry_run_src_simulator import DryRunSrcSimulator
from infrastructure.ledger.quantum_src_ledger import QuantumSrcLedger
from infrastructure.persistence.in_memory_policy_repository import (
    InMemoryPolicyRepository,
)


class SrcOrchestrator:
    """Facade hợp nhất Clean Architecture cho phân hệ SRC."""

    def __init__(self) -> None:
        self.repository = InMemoryPolicyRepository()
        self.use_case = EvaluateSecurityPolicyUseCase(self.repository)

    def evaluate_policy(self, policy_id: str, resource: str) -> dict[str, Any]:
        """Evaluate a security policy for a given resource and return a signed proof.

        Parameters:
            policy_id: Identifier of the policy to evaluate.
            resource: Target resource being evaluated under the policy.

        Returns:
            A dictionary with keys `policy_id`, `result` (evaluation outcome), and
            `quantum_proof` (an auditable proof generated by the quantum ledger).
        """
        # Execute the application use case to produce the evaluation result.
        result = self.use_case.execute(policy_id, resource)
        # Create an auditable, tamper-evident proof using the quantum ledger.
        proof = QuantumSrcLedger.generate_src_proof(policy_id, result)
        return {
            "policy_id": policy_id,
            "result": result,
            "quantum_proof": proof,
        }

    def simulate_policy_change(self, policy_id: str, new_rule_id: str) -> dict[str, Any]:
        """Simulate a policy change and return the predicted impact.

        Parameters:
            policy_id: Identifier of the existing policy.
            new_rule_id: Identifier of the rule to be added/changed for simulation.

        Returns:
            A dictionary describing the result of the dry-run simulation.
        """
        # Run the dry-run simulator to preview the effect of the policy change.
        return DryRunSrcSimulator.simulate_change(policy_id, new_rule_id)
